### PR TITLE
fix DependencyFinder::getParameterDependency for non class types

### PR DESCRIPTION
**Pull request by midahp**
array dependencies don't seem to work anymore with the newest commits. We need to detect if the parameter type is a class or not.

I don't know if this is the best way to do this, but it does seem to work.

### CODE REVIEW

**Comment by midahp** [comment]
@ralflang  An example for this problem are classes that depend on `Horde\Core\Config\State;`
`State` has an optional dependency of type array: https://github.com/maintaina-com/Core/blob/FRAMEWORK_6_0/src/Config/State.php#L39.

So we want to return the default value `null` for this parameter, but currently the code does not reach the line https://github.com/maintaina-com/Injector/blob/FRAMEWORK_6_0/src/DependencyFinder.php#L77 and instead does `return $injector->getInstance('array');` in line 72 which fails.

**Comment by ralflang** [comment]
Agreed: If an item is auto-wired and the constructor parameter is an array with default null, it should insert the default null rather than an empty array.

**Comment by ralflang** [comment]
Thank you for raising this issue.

I have added a unit test. Reading your PR is a little hard as it contains a lot of cs/ws fixes unrelated to the patch. I will try nevertheless :)

**Comment by ralflang** [comment]
@midahp 
Please consider my latest patch. It makes my unit test pass but is a little simpler than your approach. Can you check if it fixes your use case?

**Comment by midahp** [comment]
> @midahp Please consider my latest patch. It makes my unit test pass but is a little simpler than your approach. Can you check if it fixes your use case?

Yes that seems to work. Using the `isBuiltin` method is much nicer way to do this. I close this PR now.

**Pull request closed without merging**
